### ISSUE TITLE
非常好 安装成功，希望能更多的汉化

### ISSUE THREAD

**Issue by zhouaini528** [wanthings/phabricator-zh_CN#1]
非常好 安装成功，希望能更多的汉化

**Comment by llitfkitfk** [comment]
已更新

**Comment by llitfkitfk** [comment]
@zhouaini528 翻译上如果有错误或者别扭的地方请指正！

**Comment by flybeta1988** [comment]
按照readme添加后出现以下错误：
Two subclasses of "PhutilLocale" ("PhutilCNChineseLocale" and "PhutilSimplifiedChineseChinaLocale") define locales with the same locale code ("zh_CN"). Each locale must have a unique locale code.

另外：http://issue.wanthings.com/settings/panel/account/ 无法访问。

**Comment by lizaifang** [comment]
@flybeta1988 请参考[Issue5](https://github.com/wanthings/phabricator-zh_CN/issues/5#event-708567458)
另外地址是你自己的,  后面跟上`/settings/panel/account/`就可以
