### ISSUE TITLE
phabricator说已经注册了zh_CN可是遍寻不着。。。

### ISSUE THREAD

**Issue by fanvil** [wanthings/phabricator-zh_CN#5]
phabricator新版选项里有中文，但是基本上一个中文字都见不到~而且找不到中文的继承类，找不到输出zh_CN locale的方法，可是你的插件又无法安装~郁闷了

**Comment by lizaifang** [comment]
如果你的`Phabricator`是`master`分支, 请删除翻译项目中的`PhutilCNChineseLocale.php`
目前我在hash为`dc9283b85d713a9e8530ae3a3a2007e97da054a3`的版本中, 做以上操作就可以了
